### ISSUE TITLE
Linux support / help wanted ?

### ISSUE THREAD

**Issue by fabienheureux** [JackMordaunt/nativefier#1]
Hey :wave: 

Just discovered this project, seems like I am your first star :1st_place_medal: 
I am not a rust developper but would love to help you bring this project linux support (and I played a bit with some rust projects in the past).

Do you have an idea if this could be doable right now ? Or does the project needs some kind of refactoring ?

**Comment by JackMordaunt** [comment]
Thanks for the interest :) 

I have thus far ignored Linux because it's so varied in terms of package management, and I haven't had a Linux box to develop on.

Linux support merely requires code to create a standalone application with an icon, a "bundle".
It should be as simple as adding a bundler impl that performs the Linux specific bundling in [`src/bundle.rs`](https://github.com/JackMordaunt/nativefier/blob/ec7e10ea0f4f30bbd7f82146700d397e7b2215d6/src/bundle.rs)

The tricky part is deciding what that bundle should be. One way forward would be to target flatpak or snap formats, or perhaps even both and ignore the rest (apt, dpkg, pacman, eopkg, etc). Even just spitting out a shell script that has the binary embedded within could work - but that definitely wouldn't feel "native". 

Thoughts?

**Comment by fabienheureux** [comment]
Well, package management aside, there is a quite standard way to add an icon to desktop environment in Linux (for those who use one...for the others, I think that they use bash aliases). 
For Gnome and KDE, that are widely adopted accross the linux community, it requires one file creation: https://unix.stackexchange.com/a/103222

About pacman, apt etc: I think that this is not the issue here, as nativefier does not need to distribute *nativefied* apps, but simply:
- Put the binaries somewhere
- Add an icon to the window manager to feel native

I will look into it if you are open to PRs

**Comment by JackMordaunt** [comment]
If I understand correctly `.desktop` file will work for at least gnome and kde, and maybe some other desktops that are "freedesktop.org" compliant. Seems like a decent start. 

In terms of structure I think a `FreeDesktop` struct that impls `Bundler` would make it clear that we are targetting the `freedesktop.org` standard.

Regarding implemenation it looks like all we need is a `.desktop` file that calls `nativefier <url> inline` to launch the webview.

PRs welcome, let me know if you have any questions.

**Comment by fabienheureux** [comment]
This is what javascript nativefier project planned to do a while ago: https://github.com/jiahaog/nativefier/issues/204#issuecomment-450875455

I will look into it this weekend (quite busy with work stuff atm)
